apiVersion: apps/v1
kind: Deployment
metadata:
  name: interrogator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interrogator
  template:
    metadata:
      labels:
        app: interrogator
    spec:
      containers:
      - name: interrogator-container
        image: ghcr.io/sfxworks/interrogator-http:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: interrogator-service
spec:
  type: ClusterIP
  selector:
    app: interrogator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
